services/web/src/blueprints/pages/views.py
## IMPORT FLASK 
from flask import render_template, Blueprint, request, make_response, jsonify, redirect, url_for

## IMPORT MODULES
import json, os, redis
from rq import Queue, Connection

## IMPORT TASKS
from src.tasks import background_task

## DEFINE BLUEPRINT
page = Blueprint('page', __name__, template_folder='templates')

## ROUTE: INDEX
@page.route("/", methods=['GET', 'POST'])
def index():
    return render_template('index.html')

## ROUTE: TASKS DEMO
@page.route("/task", methods=['GET'])
def add_task():
    ## GET SUBMITTED STRING
    if request.args.get("n"):
        ## 
        with Connection(redis.from_url(os.getenv('REDIS_URL', 'redis://:Pa55w0rd@redis:6379/0'))):
            ## CREATE JOB
            q = Queue()
            job = q.enqueue(background_task, request.args.get("n"))

            ## CALCULATE NUMBER OF JOBS IN QUEUE
            q_len = len(q)

            ## RETURN CONFIRMATION
            return f"Task { job.id } added to the Queue at { job.enqueued_at }. { q_len } tasks in the queue"
            

    ## ERROR HANDLE
    return "No Value Received :("

## ROUTE SOCKET EXAMPLE (CHAT)
@page.route('/socket', methods=['GET'])
def socket():
    return render_template('socket.html')

services/web/src/blueprints/pages/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Hello World!</h1>

<p>Socket Demo .................... <a href="{{ url_for('page.socket') }}">link</a></p>
<p>Task Demo .................... <a href="{{ url_for('page.add_task', n='helloworld') }}">link</a></p>
<p>Task Message Endpoint .................... <a href="{{ url_for('api.testRoute') }}">link</a></p>
{% endblock %}

services/web/src/blueprints/pages/templates/socket.html
{% extends "base.html" %}

{% block head %}
<script type="text/javascript" src="https://code.jquery.com/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.3.2/socket.io.min.js"></script>
<script type="text/javascript" charset="utf-8">
    // DEFINE SOCKET
    var socket
    
    // WHEN DOCUMENT IS READY
    $(document).ready(function(){
        // CONNECT TO SOCKET
        socket = io.connect('http://' + document.domain + ':' + location.port);

        // HANDLE SENDING MESSAGE
        socket.on('connect', function(){
            // SEND INITIAL CONNECTION MESSAGE
            socket.send("Client Connected!");
        });

        // HANDLE MESSAGE UPDATES
        socket.on('message', function(msg){
            $('#chat').val($('#chat').val() + msg + '\n');
            $('#chat').scrollTop($('#chat')[0].scrollHeight);
        });

        // HANDLE MESSAGE UPDATES (API)
        socket.on('messageAPI', function(msg){
            $('#chat').val($('#chat').val() + msg + '\n');
            $('#chat').scrollTop($('#chat')[0].scrollHeight);
        });

        // HANDLE ENTER KEYPRESS
        $('#text').keypress(function(e) {
            var code = e.keyCode || e.which;
            if (code == 13) {                                
                socket.send($('#text').val());
                $('#text').val('');
            }
        });
    });

    // HANDLE CLOSING SOCKET
    function leave_room() {
        socket.emit('left', {}, function() {
            // DISCONNECT FROM SOCKET
            socket.disconnect();

            // REDIRECT BACK TO HOMEPAGE
            window.location.href = "{{ url_for('page.index') }}";
        });
    }
</script>
{% endblock %}


{% block content %}
<h1>Socket Example</h1>

<h3>Socket Messages</h3>
<textarea id="chat" cols="80" rows="20"></textarea><br><br>
<input id="text" size="80" placeholder="Enter your message here"><br><br>
<a href="#" onclick="leave_room();">Leave this room</a

{% endblock %}